### ISSUE TITLE
Poorer performance than expected.

### ISSUE THREAD

**Issue by simonjonnemeth** [Darwin-Rist/test-1#2]
It doesn't perform as good as the old MMJR builds for me. I wouldn't have a clue why that would be.

**Comment by Kleidis** [comment]
> It doesn't perform as good as the old MMJR builds for me. I wouldn't have a clue why that would be.

This is BETA software what did you expect

**Comment by sspacelynx** [comment]
Yes you fucking donkey, this is a testing repository and people should not come here.
